### ISSUE TITLE
How to evaluate

### ISSUE THREAD

**Issue by FireWallDragonDarkFluid** [Tony-Lowe/RotationDrag#2]
Hi, thanks for sharing the work.

Wondering if your are going to release the code for evalutations done in the paper. Say, in the paper, there are accurarcy comparisons between different operations in Table 1.

**Comment by Tony-Lowe** [comment]
Hi, thanks for your attention.

You can find DIFT homography evaluation code in its official repository [here](https://github.com/Tsingularity/dift/blob/main/eval_homography.py). Due to VRAM constraints, we compute accuracy on the resolution of 768 * 768 and use RANSAC to calculate homography.
